# RDS variables
variable "database_instance_class" {}
variable "availability_zone_1" {}
variable "database_instance_identifier" {}
variable "multi_az_deployment" {}
variable "database_security_group_id" {}  
variable "db_username" {}
variable "db_password" {}
variable "db_name"     {}