# alb variables
variable "project_nam" {}
variable "environment" {}
variable "alb_security_group.id" {}
variable "public_subnet_az1.id" {}
variable "public_subnet_az2.id" {}
variable "target_type" {}
variable "vpc_id" {}
variable "acm_certificate.arn" {}